"""
MATLAB Code Generator

Generates complete MATLAB simulation scripts.
"""

import numpy as np


class MatlabCodeGenerator:
    """Generates complete MATLAB simulation code."""
    
    def __init__(self, config, verbose=False):
        self.config = config
        self.verbose = verbose
    
    def generate_complete_script(self, geometry_code, material_code):
        """Generate complete MATLAB simulation script."""
        
        # Header
        header = self._generate_header()
        
        # Options
        options = self._generate_options()
        
        # Geometry (already provided)
        geometry = geometry_code
        
        # Materials (already provided)
        materials = material_code
        
        # Comparticle creation
        comparticle = self._generate_comparticle()
        
        # BEM solver
        bem_solver = self._generate_bem_solver()
        
        # Excitation
        excitation = self._generate_excitation()
        
        # Wavelength loop
        wavelength_loop = self._generate_wavelength_loop()
        
        # Save results
        save_results = self._generate_save_results()
        
        # Footer
        footer = self._generate_footer()
        
        # Combine all parts
        complete_code = f"""{header}

{options}

{geometry}

{materials}

{comparticle}

{bem_solver}

{excitation}

{wavelength_loop}

{save_results}

{footer}
"""
        return complete_code
    
    def _generate_header(self):
        """Generate script header."""
        code = """% MNPBEM Simulation Script
% Auto-generated by MNPBEM Automation Pipeline
%
% DO NOT EDIT THIS FILE MANUALLY
% Modify the configuration file instead and regenerate

clear all;
close all;
clc;

fprintf('=== MNPBEM Simulation Started ===\\n');
fprintf('Structure: %s\\n', '{structure}');
fprintf('Simulation Type: %s\\n', '{sim_type}');
""".format(
            structure=self.config['structure'],
            sim_type=self.config['simulation_type']
        )
        return code
    
    def _generate_options(self):
        """Generate BEM options."""
        sim_type = self.config['simulation_type']
        interp = self.config.get('interp', 'curv')
        waitbar = self.config.get('waitbar', 0)
        refine = self.config.get('refine', 2)
        
        code = f"""
%% BEM Options
op = bemoptions('sim', '{sim_type}', 'interp', '{interp}', 'waitbar', {waitbar}, 'refine', {refine});
fprintf('BEM options configured\\n');
"""
        return code
    
    def _generate_comparticle(self):
        """Generate comparticle object creation."""
        code = """
%% Create COMPARTICLE Object
fprintf('Creating particle structure...\\n');
p = comparticle(epstab, particles, inout, closed, op);
fprintf('Particle structure created\\n');
fprintf('  Total boundary elements: %d\\n', size(p.faces, 1));
"""
        return code
    
    def _generate_bem_solver(self):
        """Generate BEM solver initialization."""
        code = """
%% Initialize BEM Solver
fprintf('Initializing BEM solver...\\n');
bem = bemsolver(p, op);
fprintf('BEM solver initialized\\n');
"""
        return code
    
    def _generate_excitation(self):
        """Generate excitation code based on type."""
        exc_type = self.config['excitation_type']
        
        if exc_type == 'planewave':
            return self._generate_planewave_excitation()
        elif exc_type == 'dipole':
            return self._generate_dipole_excitation()
        elif exc_type == 'eels':
            return self._generate_eels_excitation()
        else:
            raise ValueError(f"Unknown excitation type: {exc_type}")
    
    def _format_matlab_array(self, array_2d):
        """
        Format 2D array for MATLAB.
        
        Args:
            array_2d: List of lists, e.g., [[1, 0, 0], [0, 1, 0]]
        
        Returns:
            str: MATLAB-formatted array string
        """
        if not array_2d:
            return "[]"
        
        rows = []
        for row in array_2d:
            row_str = ", ".join(str(val) for val in row)
            rows.append(row_str)
        
        # Join rows with semicolons for MATLAB matrix format
        return "[" + "; ".join(rows) + "]"
    
    def _generate_planewave_excitation(self):
        """Generate planewave excitation code."""
        polarizations = self.config['polarizations']
        prop_dirs = self.config.get('propagation_dirs')
        
        # If propagation directions not specified, use default [0,0,1]
        if prop_dirs is None:
            prop_dirs = [[0, 0, 1]] * len(polarizations)
        
        # Format polarizations as MATLAB array
        pol_str = self._format_matlab_array(polarizations)
        dir_str = self._format_matlab_array(prop_dirs)
        
        code = f"""
%% Plane Wave Excitation
pol = {pol_str};
dir = {dir_str};
exc = planewave(pol, dir, op);
fprintf('Plane wave excitation configured\\n');
fprintf('  Number of polarizations: %d\\n', size(pol, 1));
"""
        return code
    
    def _generate_dipole_excitation(self):
        """Generate dipole excitation code."""
        position = self.config.get('dipole_position', [0, 0, 15])
        moment = self.config.get('dipole_moment', [1, 0, 0])
        
        pos_str = f"[{position[0]}, {position[1]}, {position[2]}]"
        mom_str = f"[{moment[0]}, {moment[1]}, {moment[2]}]"
        
        code = f"""
%% Dipole Excitation
dipole_pos = {pos_str};
dipole_moment = {mom_str};
exc = dipole(dipole_moment, dipole_pos, op);
fprintf('Dipole excitation configured\\n');
"""
        return code
    
    def _generate_eels_excitation(self):
        """Generate EELS excitation code."""
        impact_param = self.config.get('impact_parameter', [10, 0])
        beam_energy = self.config.get('beam_energy', 200e3)
        beam_width = self.config.get('beam_width', 0.2)
        
        code = f"""
%% EELS Excitation
impact_param = [{impact_param[0]}, {impact_param[1]}];
beam_energy = {beam_energy};
beam_width = {beam_width};
vel = eelsbase.ene2vel(beam_energy);
exc = electronbeam(p, impact_param, beam_width, vel, op);
fprintf('EELS excitation configured\\n');
"""
        return code
    
    def _generate_wavelength_loop(self):
        """Generate wavelength loop for BEM simulation with enhanced progress display."""
        wavelength_range = self.config['wavelength_range']
        
        code = f"""
%% Wavelength Loop
wavelength_range = [{wavelength_range[0]}, {wavelength_range[1]}, {wavelength_range[2]}];
enei = linspace(wavelength_range(1), wavelength_range(2), wavelength_range(3));
n_wavelengths = length(enei);
n_polarizations = size(pol, 1);

fprintf('\\n');
fprintf('================================================================\\n');
fprintf('              Starting BEM Calculation\\n');
fprintf('================================================================\\n');
fprintf('Wavelength range: %.1f - %.1f nm\\n', wavelength_range(1), wavelength_range(2));
fprintf('Number of wavelengths: %d\\n', n_wavelengths);
fprintf('Number of polarizations: %d\\n', n_polarizations);
fprintf('----------------------------------------------------------------\\n');

% Initialize result arrays
sca = zeros(n_wavelengths, n_polarizations);
ext = zeros(n_wavelengths, n_polarizations);
abs_cross = zeros(n_wavelengths, n_polarizations);

% Start timer
calculation_start = tic;

% Loop over wavelengths
for ien = 1:n_wavelengths
    % Calculate progress percentage
    progress_pct = (ien-1) / n_wavelengths * 100;
    
    % Create progress bar (simple text-based)
    bar_length = 40;
    filled = floor(bar_length * (ien-1) / n_wavelengths);
    bar = ['[' repmat('=', 1, filled) repmat('.', 1, bar_length-filled) ']'];
    
    % Print progress header
    fprintf('\\n');
    fprintf('Progress: %s %.1f%%\\n', bar, progress_pct);
    fprintf('Wavelength %d/%d: %.2f nm', ien, n_wavelengths, enei(ien));
    
    % Solve BEM system (with timing)
    wavelength_start = tic;
    sig = bem \\ exc(p, enei(ien));
    wavelength_time = toc(wavelength_start);
    
    % Calculate cross sections
    sca(ien, :) = exc.sca(sig);
    ext(ien, :) = exc.ext(sig);
    abs_cross(ien, :) = exc.abs(sig);
    
    % Print results for first polarization
    fprintf(' - Completed in %.2f sec\\n', wavelength_time);
    fprintf('  Scattering: %.4e nm^2\\n', sca(ien, 1));
    fprintf('  Extinction: %.4e nm^2\\n', ext(ien, 1));
    fprintf('  Absorption: %.4e nm^2\\n', abs_cross(ien, 1));
    
    % Estimate remaining time
    if ien > 1
        elapsed_time = toc(calculation_start);
        avg_time_per_wavelength = elapsed_time / ien;
        remaining_wavelengths = n_wavelengths - ien;
        estimated_remaining = avg_time_per_wavelength * remaining_wavelengths;
        
        % Format time
        if estimated_remaining < 60
            time_str = sprintf('%.0f sec', estimated_remaining);
        elseif estimated_remaining < 3600
            time_str = sprintf('%.1f min', estimated_remaining/60);
        else
            time_str = sprintf('%.1f hr', estimated_remaining/3600);
        end
        
        fprintf('  Estimated time remaining: %s\\n', time_str);
    end
end

% Final progress bar
fprintf('\\n');
fprintf('Progress: [%s] 100.0%%\\n', repmat('=', 1, 40));
fprintf('----------------------------------------------------------------\\n');

% Calculate total time
total_time = toc(calculation_start);
if total_time < 60
    time_str = sprintf('%.2f seconds', total_time);
elseif total_time < 3600
    time_str = sprintf('%.2f minutes', total_time/60);
else
    time_str = sprintf('%.2f hours', total_time/3600);
end

fprintf('\\n');
fprintf('================================================================\\n');
fprintf('              BEM Calculation Complete\\n');
fprintf('================================================================\\n');
fprintf('Total computation time: %s\\n', time_str);
fprintf('Average time per wavelength: %.2f sec\\n', total_time/n_wavelengths);
fprintf('----------------------------------------------------------------\\n');
"""
        return code
    
    def _generate_save_results(self):
        """Generate code to save results."""
        import os
        output_dir = self.config['output_dir']
        output_prefix = self.config.get('output_prefix', 'simulation')
        
        # Convert to absolute path if it's relative
        if not os.path.isabs(output_dir):
            # It's a relative path - make it relative to project root
            code = f"""
%% Save Results
fprintf('\\nSaving results...\\n');

% Get absolute path to output directory
% MATLAB is running in simulation/ folder, so we need to go up one level
current_dir = pwd;
parent_dir = fileparts(current_dir);
output_dir = fullfile(parent_dir, '{output_dir}');
"""
        else:
            # It's already an absolute path - use it directly
            code = f"""
%% Save Results
fprintf('\\nSaving results...\\n');

% Use absolute path directly
output_dir = '{output_dir}';
"""
        
        # Common code for both cases
        code += f"""
% Create output directory if it doesn't exist
if ~exist(output_dir, 'dir')
    mkdir(output_dir);
    fprintf('Created output directory: %s\\n', output_dir);
end

% Save results as text file
output_file = fullfile(output_dir, '{output_prefix}_results.txt');
fid = fopen(output_file, 'w');
fprintf(fid, 'Wavelength(nm)\\t');
for i = 1:n_polarizations
    fprintf(fid, 'Sca%d(nm2)\\t', i);
end
for i = 1:n_polarizations
    fprintf(fid, 'Ext%d(nm2)\\t', i);
end
for i = 1:n_polarizations
    if i < n_polarizations
        fprintf(fid, 'Abs%d(nm2)\\t', i);
    else
        fprintf(fid, 'Abs%d(nm2)\\n', i);
    end
end

for ien = 1:n_wavelengths
    fprintf(fid, '%.4f\\t', enei(ien));
    for i = 1:n_polarizations
        fprintf(fid, '%.6e\\t', sca(ien, i));
    end
    for i = 1:n_polarizations
        fprintf(fid, '%.6e\\t', ext(ien, i));
    end
    for i = 1:n_polarizations
        fprintf(fid, '%.6e\\t', abs_cross(ien, i));
    end
    fprintf(fid, '\\n');
end

fclose(fid);
fprintf('✓ Results saved to: %s\\n', output_file);

% Also save as .mat file for MATLAB
mat_file = fullfile(output_dir, '{output_prefix}_results.mat');
save(mat_file, 'enei', 'sca', 'ext', 'abs_cross', 'pol', 'dir');
fprintf('✓ MATLAB data saved to: %s\\n', mat_file);
"""
        return code
    
    def _generate_footer(self):
        """Generate script footer."""
        code = """
%% Simulation Complete
fprintf('\\n');
fprintf('================================================================\\n');
fprintf('         MNPBEM Simulation Finished Successfully!\\n');
fprintf('================================================================\\n');
fprintf('Results have been saved to the output directory.\\n');
fprintf('\\n');
"""
        return code