% MNPBEM Simulation Script
% Auto-generated by MNPBEM Automation Pipeline
%
% DO NOT EDIT THIS FILE MANUALLY
% Modify the configuration file instead and regenerate

clear all;
close all;
clc;

fprintf('=== MNPBEM Simulation Started ===\n');
fprintf('Structure: %s\n', 'sphere');
fprintf('Simulation Type: %s\n', 'stat');



%% BEM Options
op = bemoptions('sim', 'stat', 'interp', 'curv', 'waitbar', 0, 'refine', 2);
fprintf('BEM options configured\n');



%% Geometry: Single Sphere
diameter = 50;
p = trisphere(144, diameter);
particles = {p};



%% Materials and Dielectric Functions
epstab = { epsconst(1.33^2), epstable('/home/yoojk20/workspace/MNPBEM/Material/@epstable/gold.dat') };

%% Material Mapping
inout = [2, 1];

%% Closed Surfaces
closed = 1;



%% Create COMPARTICLE Object
fprintf('Creating particle structure...\n');
p = comparticle(epstab, particles, inout, closed, op);
fprintf('Particle structure created\n');
fprintf('  Total boundary elements: %d\n', size(p.faces, 1));



%% Initialize BEM Solver
fprintf('Initializing BEM solver...\n');
bem = bemsolver(p, op);
fprintf('BEM solver initialized\n');



%% Plane Wave Excitation
pol = [1, 0, 0];
dir = [0, 0, 1];
exc = planewave(pol, dir, op);
fprintf('Plane wave excitation configured\n');
fprintf('  Number of polarizations: %d\n', size(pol, 1));



%% Wavelength Loop
wavelength_range = [400, 800, 100];
enei = linspace(wavelength_range(1), wavelength_range(2), wavelength_range(3));
n_wavelengths = length(enei);
n_polarizations = size(pol, 1);

fprintf('\n');
fprintf('================================================================\n');
fprintf('              Starting BEM Calculation\n');
fprintf('================================================================\n');
fprintf('Wavelength range: %.1f - %.1f nm\n', wavelength_range(1), wavelength_range(2));
fprintf('Number of wavelengths: %d\n', n_wavelengths);
fprintf('Number of polarizations: %d\n', n_polarizations);
fprintf('----------------------------------------------------------------\n');

% Initialize result arrays
sca = zeros(n_wavelengths, n_polarizations);
ext = zeros(n_wavelengths, n_polarizations);
abs_cross = zeros(n_wavelengths, n_polarizations);

% Start timer
calculation_start = tic;

% Loop over wavelengths
for ien = 1:n_wavelengths
    % Calculate progress percentage
    progress_pct = (ien-1) / n_wavelengths * 100;
    
    % Create progress bar (simple text-based)
    bar_length = 40;
    filled = floor(bar_length * (ien-1) / n_wavelengths);
    bar = ['[' repmat('=', 1, filled) repmat('.', 1, bar_length-filled) ']'];
    
    % Print progress header
    fprintf('\n');
    fprintf('Progress: %s %.1f%%\n', bar, progress_pct);
    fprintf('Wavelength %d/%d: %.2f nm', ien, n_wavelengths, enei(ien));
    
    % Solve BEM system (with timing)
    wavelength_start = tic;
    sig = bem \ exc(p, enei(ien));
    wavelength_time = toc(wavelength_start);
    
    % Calculate cross sections
    sca(ien, :) = exc.sca(sig);
    ext(ien, :) = exc.ext(sig);
    abs_cross(ien, :) = exc.abs(sig);
    
    % Print results for first polarization
    fprintf(' - Completed in %.2f sec\n', wavelength_time);
    fprintf('  Scattering: %.4e nm^2\n', sca(ien, 1));
    fprintf('  Extinction: %.4e nm^2\n', ext(ien, 1));
    fprintf('  Absorption: %.4e nm^2\n', abs_cross(ien, 1));
    
    % Estimate remaining time
    if ien > 1
        elapsed_time = toc(calculation_start);
        avg_time_per_wavelength = elapsed_time / ien;
        remaining_wavelengths = n_wavelengths - ien;
        estimated_remaining = avg_time_per_wavelength * remaining_wavelengths;
        
        % Format time
        if estimated_remaining < 60
            time_str = sprintf('%.0f sec', estimated_remaining);
        elseif estimated_remaining < 3600
            time_str = sprintf('%.1f min', estimated_remaining/60);
        else
            time_str = sprintf('%.1f hr', estimated_remaining/3600);
        end
        
        fprintf('  Estimated time remaining: %s\n', time_str);
    end
end

% Final progress bar
fprintf('\n');
fprintf('Progress: [%s] 100.0%%\n', repmat('=', 1, 40));
fprintf('----------------------------------------------------------------\n');

% Calculate total time
total_time = toc(calculation_start);
if total_time < 60
    time_str = sprintf('%.2f seconds', total_time);
elseif total_time < 3600
    time_str = sprintf('%.2f minutes', total_time/60);
else
    time_str = sprintf('%.2f hours', total_time/3600);
end

fprintf('\n');
fprintf('================================================================\n');
fprintf('              BEM Calculation Complete\n');
fprintf('================================================================\n');
fprintf('Total computation time: %s\n', time_str);
fprintf('Average time per wavelength: %.2f sec\n', total_time/n_wavelengths);
fprintf('----------------------------------------------------------------\n');



%% Save Results
fprintf('\nSaving results...\n');

% Get absolute path to output directory
% MATLAB is running in simulation/ folder, so we need to go up one level
current_dir = pwd;
parent_dir = fileparts(current_dir);
output_dir = fullfile(parent_dir, './results');

% Create output directory if it doesn't exist
if ~exist(output_dir, 'dir')
    mkdir(output_dir);
    fprintf('Created output directory: %s\n', output_dir);
end

% Save results as text file
output_file = fullfile(output_dir, 'simulation_results.txt');
fid = fopen(output_file, 'w');
fprintf(fid, 'Wavelength(nm)\t');
for i = 1:n_polarizations
    fprintf(fid, 'Sca%d(nm2)\t', i);
end
for i = 1:n_polarizations
    fprintf(fid, 'Ext%d(nm2)\t', i);
end
for i = 1:n_polarizations
    if i < n_polarizations
        fprintf(fid, 'Abs%d(nm2)\t', i);
    else
        fprintf(fid, 'Abs%d(nm2)\n', i);
    end
end

for ien = 1:n_wavelengths
    fprintf(fid, '%.4f\t', enei(ien));
    for i = 1:n_polarizations
        fprintf(fid, '%.6e\t', sca(ien, i));
    end
    for i = 1:n_polarizations
        fprintf(fid, '%.6e\t', ext(ien, i));
    end
    for i = 1:n_polarizations
        fprintf(fid, '%.6e\t', abs_cross(ien, i));
    end
    fprintf(fid, '\n');
end

fclose(fid);
fprintf('✓ Results saved to: %s\n', output_file);

% Also save as .mat file for MATLAB
mat_file = fullfile(output_dir, 'simulation_results.mat');
save(mat_file, 'enei', 'sca', 'ext', 'abs_cross', 'pol', 'dir');
fprintf('✓ MATLAB data saved to: %s\n', mat_file);



%% Simulation Complete
fprintf('\n');
fprintf('================================================================\n');
fprintf('         MNPBEM Simulation Finished Successfully!\n');
fprintf('================================================================\n');
fprintf('Results have been saved to the output directory.\n');
fprintf('\n');

